services:
  lontra:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8080'
    networks:
      - tre
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/lontra"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tre:
    driver: bridge
